export const investigaciones = [
  {
    id: 1,
    name: "Mal de Hansen",
    image: "/articulos/Mal de Hansen.jpg",
    abstract:
      "Para exponer algo sobre contagio daré un breve resumen sobre las conclusiones que llegó la comisión de leprólogos nombrados para este fin en Filipinas (1936). 1-Todo leproso bacteriológicamente positivo debe ser considerado como fuente de infección y de contagio que es...",
    autor: "Dr. Jacinto Convit",
    year: 1941,
    pdf: "/articulos/Mal-de-Hansen.pdf",
  },
  {
    id: 2,
    name: "Consideraciones sobre el enfermo dado de alta y a otros tópicos en relación a la lepra",
    image: "/articulos/relacion-a-la-lepra.jpg",
    abstract: "La enfermedad afecta principalmente a la piel, los nervios, la mucosa de las vías respiratorias superiores y los ojos. En algunos casos los síntomas pueden aparecer a los 9 meses después de haber adquirido la infección y en otros casos pueden tardar hasta 20 años.",
    autor: "Dr. Jacinto Convit",
    year: 1943,
    pdf: "/articulos/relacion-a-la-lepra.pdf",
  },
  {
    id: 3,
    name: "Lesiones leprosas del cuero cabelludo",
    image: "/articulos/lesiones-leprosas-del-cuero-cabelludo.jpg",
    abstract: "La lepra afecta sobre todo la piel y los nervios periféricos. Las complicaciones más graves son las que resultan de la pérdida del sentido del tacto, de la sensación de dolor y la temperatura; la debilidad muscular que puede causar deformidades; y las lesiones desfigurantes de la piel y la mucosa nasal.",
    autor: "Dr. Jacinto Convit",
    year: 1943,
    pdf: "/articulos/lesiones-leprosas-del-cuero-cabelludo.pdf",
  },
  {
    id: 4,
    name: "La vitamina E",
    image: "/articulos/la-vitamina-e.jpg",
    abstract: "Consumir vitamina E en alimentos no es riesgoso ni dañino. Sin embargo, las dosis altas de suplementos de vitamina E (suplementos de alfa-tocoferol) podrían incrementar el riesgo de hemorragia cerebral (accidente cerebrovascular hemorrágico).",
    autor: "Dr. Jacinto Convit",
    year: 1943,
    
    pdf: "/articulos/la-vitamina-e.pdf",
  },
  {
    id: 5,
    name: "Immunotherapy and immunoprophylaxis of leprosy",
    image: "/articulos/Immunotherapy-and-immunoprophylaxis.png",
    abstract: "There is substantial evidence that the immunological defect which reaches its maximum expression in lepromatous patients is also present in other population groups, including a small portion of the healthy population. ",
    year: 1983,
    autor: "Dr. Jacinto Convit",
    pdf: "/articulos/Immunotherapy-and-immunoprophylaxis.pdf",
  },
  {
    id: 6,
    name: "Molecular Identification of Trypanosoma",
    image: "/articulos/Molecular Identification of Trypanosoma.png",
    abstract: "Chagas disease is an endemic zoonosis broadly distributed throughout the American Continent, representing an important health problem in 17 Latin American countries. About 100 million people of the Latin American population are at risk and 16-18 million people are estimated to be infected (WHO, 2002)",
    year: 2005,
    autor: "Dr. Jacinto Convit",
    pdf: "/articulos/Molecular Identification of Trypanosoma.pdf",
  },
  {
    id: 7,
    name: "Autologous tumor lysate",
    image: "/articulos/Autologous tumor lysate.png",
    abstract: "Introduction Autologous tumor cell vaccines rely on the concept of preserving an individual’s own tumorigenic makeup, expressing its unique set of tumor-associated antigens as well as antigenic elements from the surrounding stroma.",
    year: 2015,
    autor: "Dr. Jacinto Convit",
    pdf: "/articulos/Autologous tumor lysate.pdf",
  },
  {
    id: 8,
    name: "Vacuna contra la lepra",
    image: "/articulos/vacuna contra la lepra.png",
    abstract: "Un modelo de vacunación en lepra es llevado a cabo por un grupo de investigadores en el Instituto Nacional de Dermatología. La vacuna compuesta por Mycobacterium leprae (ML) muerto por el calor + BCG es utilizada como procedimiento inmunoterápico en un importante número de enfermos de lepra, portadores de formas difusas de la enfermedad y en contactos susceptibles de dar estas formas difusas. ",
    year: 1984,
    autor: "Dr. Jacinto Convit",
    pdf: "/articulos/vacuna contra la lepra.pdf",
  },
  {
    id: 9,
    name: "Reactividad serológica y celular frente a proteinas micobacterianas en la enfermedad de hansen",
    image: "/articulos/Reactividad serológica y celular frente a proteinas micobacterianas en la enfermedad de hansen.png",
    abstract: ". Se diseñó un estudio para evaluar la reactividad inmunológica frente a diferentes preparaciones proteicas micobacterianas utilizando pruebas serológicas y de inmunidad celular.",
    year: 2010,
    autor: "Dr. Jacinto Convit",
    pdf: "/articulos/Reactividad serológica y celular frente a proteinas micobacterianas en la enfermedad de hansen.pdf",
  },
];
