export const investigaciones = [
  {
    id: 1,
    name: "Mal de Hansen",
    image: "/articulos/1941/Mal de Hansen.jpg",
    abstract:
      "Para exponer algo sobre contagio daré un breve resumen sobre las conclusiones que llegó la comisión de leprólogos nombrados para este fin en Filipinas (1936). 1-Todo leproso bacteriológicamente positivo debe ser considerado como fuente de infección y de contagio que es...",
    autor: "Dr. Jacinto Convit",
    year: 1941,
    pdf: "/articulos/1941/Mal-de-Hansen.pdf",
  },
  {
    id: 2,
    name: "Consideraciones sobre el enfermo dado de alta y a otros tópicos en relación a la lepra",
    image: "/articulos/1943/relacion-a-la-lepra.jpg",
    abstract: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    autor: "Dr. Jacinto Convit",
    year: 1943,
    pdf: "/articulos/1943/relacion-a-la-lepra.pdf",
  },
  {
    id: 3,
    name: "Lesiones leprosas del cuero cabelludo",
    image: "/articulos/1943/lesiones-leprosas-del-cuero-cabelludo.jpg",
    abstract: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    autor: "Dr. Jacinto Convit",
    year: 1943,
    pdf: "/articulos/1943/lesiones-leprosas-del-cuero-cabelludo.pdf",
  },
  {
    id: 4,
    name: "La vitamina E",
    image: "/articulos/1943/la-vitamina-e.jpg",
    abstract: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    autor: "Dr. Jacinto Convit",
    year: 1943,
    pdf: "/articulos/1943/la-vitamina-e.pdf",
  },
  {
    id: 5,
    name: "Mal de Hansen",
    image: "/articulos/1941/Mal de Hansen.jpg",
    abstract: "",
    year: 1941,
    pdf: "/articulos/1941/Mal de Hansen.pdf",
  },
  {
    id: 6,
    name: "Mal de Hansen",
    image: "/articulos/1941/Mal de Hansen.jpg",
    abstract: "",
    year: 1941,
    pdf: "/articulos/1941/Mal de Hansen.pdf",
  },
  {
    id: 7,
    name: "Mal de Hansen",
    image: "/articulos/1941/Mal de Hansen.jpg",
    abstract: "",
    year: 1941,
    pdf: "/articulos/1941/Mal de Hansen.pdf",
  },
  {
    id: 8,
    name: "Mal de Hansen",
    image: "/articulos/1941/Mal de Hansen.jpg",
    abstract: "",
    year: 1941,
    pdf: "/articulos/1941/Mal de Hansen.pdf",
  },
  {
    id: 9,
    name: "Mal de Hansen",
    image: "/articulos/1941/Mal de Hansen.jpg",
    abstract: "",
    year: 1941,
    pdf: "/articulos/1941/Mal de Hansen.pdf",
  },
];
